# AIMedicine: разбор трёх случаев

Синтетическая когорта взрослых пациентов с внебольничной пневмонией. Клинические рекомендации — редакция 2024 года.

Карточка пациента → поиск по документу → план → сценарная динамика дня 3 → пересмотр → независимый аудит.

Notebook показывает сохранённые результаты из `reports/`: завершённый live-прогон с Mistral либо, если его нет, явно обозначенный offline-прогон. Показатели симуляции задаются сценарием; они используются для проверки переходов между этапами.

In [1]:
import json
from pathlib import Path
import pandas as pd
from IPython.display import display, Markdown

candidates = [Path.cwd(), Path.cwd().parent]
ROOT = next((p for p in candidates if (p / "aimedicine").is_dir() and (p / "reports").is_dir()), None)
if ROOT is None:
    raise RuntimeError("Откройте notebook из корня проекта или папки notebooks")
def load(path):
    return json.loads(path.read_text(encoding="utf-8"))

expected_ids = {p["id"] for p in load(ROOT / "data/patients.json")}

def completed_run(mode):
    folder = ROOT / "reports" / mode
    manifest = folder / "summary.json"
    if not manifest.exists():
        return None, "нет завершающего summary.json"
    status_file = folder / "run_status.json"
    if status_file.exists() and load(status_file).get("status") != "complete":
        return None, "run_status.json не подтверждает завершение запуска"
    summary = load(manifest)
    if summary.get("mode") != mode or summary.get("status") in {"failed", "error"}:
        return None, "режим/статус манифеста не подтверждает успешный запуск"
    if {c.get("patient_id") for c in summary.get("cases", [])} != expected_ids or len(summary["cases"]) != len(expected_ids):
        return None, "манифест не содержит полный набор трёх пациентов"
    error_file = folder / "run_error.json"
    if error_file.exists() and error_file.stat().st_mtime_ns > manifest.stat().st_mtime_ns:
        return None, "после манифеста зафиксирована ошибка запуска"
    result = []
    for row in summary["cases"]:
        report_path = (folder / row["path"]).resolve()
        if report_path.parent != folder.resolve() or not report_path.is_file():
            return None, "отсутствует файл, указанный в манифесте"
        if report_path.stat().st_mtime_ns > manifest.stat().st_mtime_ns:
            return None, "файлы менялись после манифеста; возможен незавершённый повторный запуск"
        item = load(report_path)
        if item.get("mode") != mode or item.get("patient", {}).get("id") != row["patient_id"] or not item.get("plans"):
            return None, "история не соответствует манифесту"
        result.append((report_path, item))
    return result, "полный набор подтверждён summary.json"

traces, live_status = completed_run("live")
if traces is not None:
    selected_mode = "live"
    display(Markdown("Выбран **live**: найден полный завершённый запуск с API."))
else:
    traces, offline_status = completed_run("offline")
    selected_mode = "offline"
    display(Markdown(f"Выбран **offline**. Live не подтверждён: {live_status}. Offline не заменяет проверку LLM."))
    if traces is None:
        raise RuntimeError("Нет полного offline-запуска: " + offline_status + ". Выполните python -m aimedicine.cli demo --mode offline --output reports/offline")
display(Markdown(f"Показано **{len(traces)}** сохранённых историй."))

Выбран **live**: найден полный завершённый запуск с API.

Показано **3** сохранённых историй.

## Сводка запусков

Каждый результат связан с конкретной историей и режимом. Находки приведены по записям аудита, включая исторические замечания.

In [2]:
rows = []
for path, trace in traces:
    initial = trace["plans"][0] if trace["plans"] else {}
    final = trace["plans"][-1] if trace["plans"] else {}
    def drug_names(plan):
        return ", ".join(a["title"] for a in plan.get("actions", []) if a.get("category") == "medication" and a.get("status") != "stopped")
    findings = [f for audit in trace.get("audits", []) for f in audit.get("findings", [])]
    unverified = [f for audit in trace.get("audits", []) for f in audit.get("unverified_findings", [])]
    rows.append({"Пациент": trace["patient"]["id"], "Режим": trace["mode"], "Начальная терапия": drug_names(initial), "Итоговая терапия": drug_names(final), "Версий плана": len(trace["plans"]), "Подтверждённых записей": len(findings), "Неподтверждённых гипотез LLM": len(unverified), "Нужна экспертная проверка": trace.get("metadata", {}).get("requires_human_review", "не указано"), "Файл": str(path.relative_to(ROOT))})
display(pd.DataFrame(rows))

,Пациент,Режим,Начальная терапия,Итоговая терапия,Версий плана,Подтверждённых записей,Неподтверждённых гипотез LLM,Нужна экспертная проверка,Файл
0,patient_001,live,Ампициллин,Ампициллин,2,0,0,False,reports/live/patient_001.json
1,patient_002,live,Левофлоксацин,Левофлоксацин,2,0,2,True,reports/live/patient_002.json
2,patient_003,live,Ампициллин,Левофлоксацин,2,0,2,True,reports/live/patient_003.json

## Пациенты, динамика и планы

Каждое действие показывает исходное обоснование и идентификаторы источников. Доступные показатели сравниваются по времени наблюдения. Отсутствующие данные не заменяются нулями.

In [3]:
for path, trace in traces:
    patient = trace["patient"]
    display(Markdown(f"### {patient['id']} · {trace['mode']}\n\n{patient['age']} лет; {patient['diagnosis']}. Причина госпитализации: {patient['hospitalization_reason']}"))
    display(Markdown("**Аллергии:** " + ("неизвестны" if patient.get("allergies") is None else ", ".join(patient["allergies"]) or "нет в сценарии")))
    display(Markdown("**Сопутствующие заболевания:** " + (", ".join(patient.get("comorbidities", [])) or "нет в сценарии")))
    observations = patient["observations"] + [o for c in trace.get("checkpoints", []) for o in c["patient"]["observations"]]
    frame = pd.DataFrame(observations).drop_duplicates(["name", "unit", "day"], keep="last")
    display(frame.pivot_table(index=["name", "unit"], columns="day", values="value", aggfunc="last"))
    for checkpoint in trace.get("checkpoints", []):
        display(Markdown(f"**День {checkpoint['day']}:** " + "; ".join(e["description"] for e in checkpoint.get("events", []))))
        if checkpoint.get("execution_log"):
            display(Markdown("**Журнал действий симуляции:** относительный порядок задан полем sequence; это синтетические события."))
            display(pd.DataFrame(checkpoint["execution_log"]))
        display(Markdown("Допущения: " + "; ".join(checkpoint.get("assumptions", []))))
    for plan in trace["plans"]:
        display(Markdown(f"**План {plan['version']} · день {plan['day']} · {plan['origin']}**\n\n{plan['rationale']}"))
        display(pd.DataFrame([{"Действие": a["title"], "Доза": a.get("dose"), "Частота": a.get("frequency"), "Статус": a["status"], "Обоснование": a["indication"], "Источники": ", ".join(a["evidence_ids"])} for a in plan["actions"]]))
        if plan.get("missing_data"):
            display(Markdown("Неизвестные данные: " + "; ".join(plan["missing_data"])))

### patient_001 · live

52 лет; Внебольничная пневмония. Причина госпитализации: Синтетический случай: госпитализация для наблюдения из-за выраженной слабости и невозможности организовать амбулаторное наблюдение.

**Аллергии:** нет в сценарии

**Сопутствующие заболевания:** нет в сценарии

day                                      0      3
name                  unit
alt                   U/L             21.0    NaN
ast                   U/L             23.0    NaN
chest_xray_infiltrate boolean          1.0    NaN
creatinine            µmol/L          78.0    NaN
crp                   mg/L           128.0  42.00
egfr                  mL/min/1.73m²   99.0    NaN
heart_rate            /min           104.0  84.00
potassium             mmol/L           4.2    NaN
qtc_ms                ms             420.0    NaN
respiratory_rate      /min            24.0  18.00
spo2                  %               94.0  96.00
temperature           °C              38.7  37.01
wbc                   10^9/L          14.1   9.00

**День 3:**

**Журнал действий симуляции:** относительный порядок задан полем sequence; это синтетические события.

   day  sequence               event          action_id  synthetic     drug_id
0    0         1    sputum_collected  v1:sputum_culture       True         NaN
1    0         2  medication_started   v1:ampicillin_iv       True  ampicillin

Допущения: Синтетический сценарий для проверки программной логики; физиологическая и прогностическая валидность не установлена.; Изменения показателей заданы иллюстративными правилами; случайная вариация воспроизводима по seed.; Экспозиция учитывает только active-препараты в переданном полном снимке плана.; Посев доступен при выполненном active-назначении sputum_culture до контрольного дня.; В синтетическом execution_log забор мокроты предшествует началу active-препаратов; согласия не создаются.; Статус active означает действие внутри симуляции.

**План 1 · день 0 · llm**

Пациент 52 лет с нетяжелой внебольничной пневмонией госпитализирован по социальным показаниям. Учитывая отсутствие сопутствующих заболеваний, аллергий и факторов риска инфицирования полирезистентными возбудителями, выбрана эмпирическая антибактериальная терапия с использованием ампициллина в/в. Ампициллин является препаратом выбора для данной группы пациентов согласно рекомендациям, так как сохраняет активность против основных возбудителей ВП (S. pneumoniae, H. influenzae) и имеет низкий риск резистентности в РФ. Назначение амоксициллина с клавулановой кислотой или других препаратов не требуется из-за отсутствия факторов риска и сопутствующих заболеваний.

,Действие,Доза,Частота,Статус,Обоснование,Источники
0,Ампициллин,"2,0 г",каждые 6 ч,active,Выбран в качестве препарата первого ряда для э...,"cap-empiric, cap-parenteral, cap-beta-allergy,..."
1,Микроскопия и посев мокроты с чувствительностью,None,None,active,Назначен для всех пациентов с продуктивным каш...,"cap-sputum-culture, cap-sputum-before-antibiot..."
2,Общий (клинический) анализ крови,None,None,active,Общий анализ крови необходим для оценки тяжест...,cap-cbc
3,Биохимический анализ крови,None,None,active,Биохимический анализ крови необходим для оценк...,cap-biochemistry
4,С-реактивный белок,None,None,active,Исследование уровня С-реактивного белка для оц...,"cap-crp, cap-crp-dynamics"
5,ЭКГ в стандартных отведениях,None,None,active,ЭКГ в стандартных отведениях для исключения ос...,cap-ecg
6,Пульсоксиметрия,None,None,active,Пульсоксиметрия для выявления гипоксемии и оце...,cap-pulse-oximetry
7,Контроль жизненных показателей,None,None,active,Контроль жизненных показателей для оценки тяже...,cap-vitals
8,Достаточное питьё и ограничение чрезмерной наг...,None,None,active,Достаточное питьё и ограничение чрезмерной наг...,cap-hydration
9,Оценка эффективности и безопасности через 48–7...,None,None,active,Оценка эффективности и безопасности терапии че...,"cap-reassess-72h, cap-treatment-failure, cap-c..."

**План 2 · день 3 · rule**

Положительная динамика в сценарной контрольной точке; триггеров смены антибиотика не обнаружено. Продолжение с оценкой переносимости. Переход на приём внутрь требует отдельной проверки всех критериев стабильности, включая повторные измерения температуры.

,Действие,Доза,Частота,Статус,Обоснование,Источники
0,Ампициллин,"2,0 г",каждые 6 ч,active,Выбран в качестве препарата первого ряда для э...,"cap-empiric, cap-parenteral, cap-beta-allergy,..."
1,Микроскопия и посев мокроты с чувствительностью,None,None,active,Назначен для всех пациентов с продуктивным каш...,"cap-sputum-culture, cap-sputum-before-antibiot..."
2,Общий (клинический) анализ крови,None,None,active,Общий анализ крови необходим для оценки тяжест...,cap-cbc
3,Биохимический анализ крови,None,None,active,Биохимический анализ крови необходим для оценк...,cap-biochemistry
4,С-реактивный белок,None,None,active,Исследование уровня С-реактивного белка для оц...,"cap-crp, cap-crp-dynamics"
5,ЭКГ в стандартных отведениях,None,None,active,ЭКГ в стандартных отведениях для исключения ос...,cap-ecg
6,Пульсоксиметрия,None,None,active,Пульсоксиметрия для выявления гипоксемии и оце...,cap-pulse-oximetry
7,Контроль жизненных показателей,None,None,active,Контроль жизненных показателей для оценки тяже...,cap-vitals
8,Достаточное питьё и ограничение чрезмерной наг...,None,None,active,Достаточное питьё и ограничение чрезмерной наг...,cap-hydration
9,Оценка эффективности и безопасности через 48–7...,None,None,active,Оценка эффективности и безопасности терапии че...,"cap-reassess-72h, cap-treatment-failure, cap-c..."

### patient_002 · live

57 лет; Внебольничная пневмония. Причина госпитализации: Синтетический случай: требуется наблюдение; известная немедленная аллергическая реакция на бета-лактамный антибиотик в анамнезе.

**Аллергии:** beta_lactam_immediate

**Сопутствующие заболевания:** нет в сценарии

day                                      0      3
name                  unit
alt                   U/L             18.0    NaN
ast                   U/L             20.0    NaN
chest_xray_infiltrate boolean          1.0    NaN
creatinine            µmol/L          70.0    NaN
crp                   mg/L           122.0  42.00
egfr                  mL/min/1.73m²   97.0    NaN
heart_rate            /min           102.0  84.00
potassium             mmol/L           4.2    NaN
qtc_ms                ms             419.0    NaN
respiratory_rate      /min            23.0  18.00
spo2                  %               94.0  96.00
temperature           °C              38.6  37.01
wbc                   10^9/L          13.8   9.00

**День 3:**

**Журнал действий симуляции:** относительный порядок задан полем sequence; это синтетические события.

,day,sequence,event,action_id,synthetic,drug_id
0,0,1,sputum_collected,v1:sputum_culture,True,NaN
1,0,2,medication_started,v1:levofloxacin_iv,True,levofloxacin

Допущения: Синтетический сценарий для проверки программной логики; физиологическая и прогностическая валидность не установлена.; Изменения показателей заданы иллюстративными правилами; случайная вариация воспроизводима по seed.; Экспозиция учитывает только active-препараты в переданном полном снимке плана.; Посев доступен при выполненном active-назначении sputum_culture до контрольного дня.; В синтетическом execution_log забор мокроты предшествует началу active-препаратов; согласия не создаются.; Статус active означает действие внутри симуляции.

**План 1 · день 0 · llm**

Пациентка 57 лет с нетяжелой внебольничной пневмонией госпитализирована по немедицинским показаниям. У пациентки имеется немедленная аллергическая реакция на бета-лактамные антибиотики, что исключает использование ампициллина или амоксициллина с клавулановой кислотой. На основании отсутствия сопутствующих заболеваний и факторов риска инфицирования полирезистентными возбудителями, а также нормальных показателей функции почек и отсутствия удлинения интервала QT, выбрана эмпирическая терапия с использованием левофлоксацина в/в. Левофлоксацин является респираторным фторхинолоном с широким спектром активности, включая основные возбудители внебольничной пневмонии, и подходит для парентерального применения. Также назначены необходимые обследования для мониторинга состояния и коррекции терапии.

,Действие,Доза,Частота,Статус,Обоснование,Источники
0,Левофлоксацин,"0,5 г",каждые 12 ч,active,Левофлоксацин выбран ввиду немедленной аллерги...,"cap-beta-allergy, cap-inpatient-table, cap-flu..."
1,Микроскопия и посев мокроты с чувствительностью,None,None,active,Микроскопия и посев мокроты необходимы для выя...,"cap-sputum-culture, cap-sputum-before-antibiot..."
2,Общий (клинический) анализ крови,None,None,active,Общий анализ крови необходим для оценки тяжест...,cap-cbc
3,Биохимический анализ крови,None,None,active,Биохимический анализ крови необходим для оценк...,cap-biochemistry
4,С-реактивный белок,None,None,active,С-реактивный белок используется для оценки тяж...,"cap-crp, cap-crp-dynamics"
5,ЭКГ в стандартных отведениях,None,None,active,ЭКГ в стандартных отведениях необходима для ис...,cap-ecg
6,Пульсоксиметрия,None,None,active,Пульсоксиметрия необходима для оценки уровня к...,cap-pulse-oximetry
7,Контроль жизненных показателей,None,None,active,"Контроль жизненных показателей (температура, Ч...",cap-vitals
8,Достаточное питьё и ограничение чрезмерной наг...,None,None,active,Достаточное питьё и ограничение чрезмерной наг...,cap-hydration
9,Оценка эффективности и безопасности через 48–7...,None,None,active,Оценка эффективности и безопасности терапии че...,"cap-reassess-72h, cap-treatment-failure, cap-c..."

**План 2 · день 3 · rule**

Положительная динамика в сценарной контрольной точке; триггеров смены антибиотика не обнаружено. Продолжение с оценкой переносимости. Переход на приём внутрь требует отдельной проверки всех критериев стабильности, включая повторные измерения температуры.

,Действие,Доза,Частота,Статус,Обоснование,Источники
0,Левофлоксацин,"0,5 г",каждые 12 ч,active,Левофлоксацин выбран ввиду немедленной аллерги...,"cap-beta-allergy, cap-inpatient-table, cap-flu..."
1,Микроскопия и посев мокроты с чувствительностью,None,None,active,Микроскопия и посев мокроты необходимы для выя...,"cap-sputum-culture, cap-sputum-before-antibiot..."
2,Общий (клинический) анализ крови,None,None,active,Общий анализ крови необходим для оценки тяжест...,cap-cbc
3,Биохимический анализ крови,None,None,active,Биохимический анализ крови необходим для оценк...,cap-biochemistry
4,С-реактивный белок,None,None,active,С-реактивный белок используется для оценки тяж...,"cap-crp, cap-crp-dynamics"
5,ЭКГ в стандартных отведениях,None,None,active,ЭКГ в стандартных отведениях необходима для ис...,cap-ecg
6,Пульсоксиметрия,None,None,active,Пульсоксиметрия необходима для оценки уровня к...,cap-pulse-oximetry
7,Контроль жизненных показателей,None,None,active,"Контроль жизненных показателей (температура, Ч...",cap-vitals
8,Достаточное питьё и ограничение чрезмерной наг...,None,None,active,Достаточное питьё и ограничение чрезмерной наг...,cap-hydration
9,Оценка эффективности и безопасности через 48–7...,None,None,active,Оценка эффективности и безопасности терапии че...,"cap-reassess-72h, cap-treatment-failure, cap-c..."

### patient_003 · live

49 лет; Внебольничная пневмония. Причина госпитализации: Синтетический случай: госпитализация для наблюдения при выраженной слабости и недостаточной доступности амбулаторного контроля.

**Аллергии:** нет в сценарии

**Сопутствующие заболевания:** нет в сценарии

day                                      0       3
name                  unit
alt                   U/L             21.0     NaN
ast                   U/L             23.0     NaN
chest_xray_infiltrate boolean          1.0     NaN
creatinine            µmol/L          78.0     NaN
crp                   mg/L           128.0  150.00
egfr                  mL/min/1.73m²   99.0     NaN
heart_rate            /min           104.0  106.00
potassium             mmol/L           4.2     NaN
qtc_ms                ms             420.0     NaN
respiratory_rate      /min            24.0   25.00
spo2                  %               94.0   93.00
temperature           °C              38.7   38.61
wbc                   10^9/L          14.1   15.20

**День 3:** К контрольной точке через 72 часа сохраняется лихорадка и/или отсутствует снижение воспалительного показателя: нужна переоценка.; Доступен посев Haemophilus influenzae: устойчивость к действующему препарату ampicillin; требуется пересмотр с учётом антибиотикограммы.

**Журнал действий симуляции:** относительный порядок задан полем sequence; это синтетические события.

   day  sequence               event          action_id  synthetic     drug_id
0    0         1    sputum_collected  v1:sputum_culture       True         NaN
1    0         2  medication_started   v1:ampicillin_iv       True  ampicillin

Допущения: Синтетический сценарий для проверки программной логики; физиологическая и прогностическая валидность не установлена.; Изменения показателей заданы иллюстративными правилами; случайная вариация воспроизводима по seed.; Экспозиция учитывает только active-препараты в переданном полном снимке плана.; Посев доступен при выполненном active-назначении sputum_culture до контрольного дня.; В синтетическом execution_log забор мокроты предшествует началу active-препаратов; согласия не создаются.; Статус active означает действие внутри симуляции.; Условие сценария: возбудитель устойчив к каждому активному антибиотику из каталога и чувствителен к остальным. Это заданный результат посева, не прогноз возникновения резистентности.

**План 1 · день 0 · llm**

Пациент 49 лет с нетяжелой внебольничной пневмонией, госпитализированный по социальным показаниям. У пациента отсутствуют аллергии, сопутствующие заболевания и факторы риска инфицирования полирезистентными возбудителями. Выбран эмпирический подход к антибиотикотерапии и обследованию с учетом рекомендаций для нетяжелой ВП без факторов риска.

,Действие,Доза,Частота,Статус,Обоснование,Источники
0,Ампициллин,"2,0 г",каждые 6 ч,active,Выбран ампициллин в/в как препарат первого ряд...,"cap-empiric, cap-parenteral, cap-beta-allergy,..."
1,Микроскопия и посев мокроты с чувствительностью,None,None,active,Микроскопия и посев мокроты показаны до начала...,"cap-sputum-culture, cap-sputum-before-antibiot..."
2,Общий (клинический) анализ крови,None,None,active,Общий анализ крови необходим для оценки тяжест...,cap-cbc
3,Биохимический анализ крови,None,None,active,Биохимический анализ крови необходим для оценк...,cap-biochemistry
4,С-реактивный белок,None,None,active,С-реактивный белок (СРБ) используется для оцен...,"cap-crp, cap-crp-dynamics"
5,ЭКГ в стандартных отведениях,None,None,active,ЭКГ в стандартных отведениях показана для искл...,cap-ecg
6,Пульсоксиметрия,None,None,active,Пульсоксиметрия необходима для оценки уровня к...,cap-pulse-oximetry
7,Контроль жизненных показателей,None,None,active,"Контроль жизненных показателей (температура, Ч...",cap-vitals
8,Достаточное питьё и ограничение чрезмерной наг...,None,None,active,Достаточное питье и ограничение чрезмерной физ...,cap-hydration
9,Оценка эффективности и безопасности через 48–7...,None,None,active,Оценка эффективности терапии через 48-72 часа ...,"cap-reassess-72h, cap-treatment-failure, cap-c..."

Неизвестные данные: Недостаточно данных о посеве мокроты до начала антибиотикотерапии, так как пациент уже госпитализирован и возможно начало антибиотикотерапии до сбора мокроты.

**План 2 · день 3 · llm**

Пациент 49 лет с нетяжелой внебольничной пневмонией, госпитализированный по социальным показаниям. На основании результатов посева мокроты, выявившего резистентность Haemophilus influenzae к ампициллину, и сохраняющейся лихорадки, а также отсутствия снижения уровня СРБ через 72 часа, необходимо скорректировать антибиотикотерапию. Левофлоксацин в/в выбран как препарат с доказанной эффективностью против H. influenzae и отсутствием резистентности в данном случае. Левофлоксацин активен против основных возбудителей пневмонии и имеет хорошую переносимость, что соответствует рекомендациям для нетяжелой ВП с учетом чувствительности выявленного возбудителя. Также сохраняются все необходимые обследования и мониторинговые процедуры для оценки эффективности терапии и состояния пациента.

,Действие,Доза,Частота,Статус,Обоснование,Источники
0,Левофлоксацин,"0,5 г",каждые 12 ч,active,Левофлоксацин в/в выбран в связи с резистентно...,"cap-beta-allergy, cap-inpatient-table, cap-flu..."
1,Общий (клинический) анализ крови,None,None,active,Общий анализ крови необходим для мониторинга в...,cap-cbc
2,Биохимический анализ крови,None,None,active,Биохимический анализ крови необходим для оценк...,cap-biochemistry
3,С-реактивный белок,None,None,active,С-реактивный белок используется для динамическ...,"cap-crp, cap-crp-dynamics"
4,ЭКГ в стандартных отведениях,None,None,active,ЭКГ в стандартных отведениях показана для искл...,cap-ecg
5,Микроскопия и посев мокроты с чувствительностью,None,None,active,Микроскопия и посев мокроты необходимы для под...,"cap-sputum-culture, cap-sputum-before-antibiot..."
6,Пульсоксиметрия,None,None,active,Пульсоксиметрия необходима для оценки уровня к...,cap-pulse-oximetry
7,Контроль жизненных показателей,None,None,active,Контроль жизненных показателей необходим для м...,cap-vitals
8,Достаточное питьё и ограничение чрезмерной наг...,None,None,active,Достаточное питье и ограничение физической наг...,cap-hydration
9,Оценка эффективности и безопасности через 48–7...,None,None,active,Оценка эффективности терапии через 48-72 часа ...,"cap-reassess-72h, cap-treatment-failure, cap-c..."
10,Проверка возможности перехода на приём внутрь,None,None,active,Пересмотр возможности перехода на пероральный ...,"cap-oral-switch-1, cap-oral-switch-2"

Неизвестные данные: Недостаточно данных о наличии факторов риска инфицирования полирезистентными возбудителями, которые могли бы повлиять на выбор антибиотика, кроме как резистентность к ампициллину.

## Независимый аудит

Находки правил и LLM имеют отдельную маркировку. Подтверждение связывает замечание с фактом, версией плана, действием и источником. Остальные предположения модели сохраняются отдельно для экспертной оценки. Исправленные находки остаются в истории.

Проверка покрывает заданный каталог и перечисленные правила; произвольные утверждения за их пределами автоматически не подтверждаются.

In [4]:
for path, trace in traces:
    display(Markdown(f"### {trace['patient']['id']} · {trace['mode']}"))
    if trace.get("metadata", {}).get("requires_human_review"):
        display(Markdown("**Требуется экспертная проверка.** Неподтверждённые гипотезы и недостаточные данные не считаются чистым аудитом."))
    for number, audit in enumerate(trace.get("audits", []), 1):
        display(Markdown(f"**Аудит {number}. LLM-проверка: {'да' if audit.get('llm_reviewed') else 'нет'}.**"))
        if audit.get("llm_summary"):
            display(Markdown(audit["llm_summary"]))
        records = [{"Код": f["code"], "Уровень": f["severity"], "Статус": f["status"], "Происхождение": f["origin"], "Версия": f["plan_version"], "Находка": f["message"], "Доказательство": f["patient_evidence"], "Исправление": f["recommendation"], "Источники": ", ".join(f["evidence_ids"])} for f in audit.get("findings", [])]
        display(pd.DataFrame(records)) if records else display(Markdown("Подтверждённых нарушений в покрытых проверках не найдено."))
        if audit.get("unverified_findings"):
            display(Markdown("**Неподтверждённые предположения LLM — отдельная экспертная оценка**"))
            display(pd.DataFrame([{"Код": f["code"], "Версия": f["plan_version"], "Гипотеза": f["message"], "Заявленное основание": f["patient_evidence"], "Источники": ", ".join(f["evidence_ids"])} for f in audit["unverified_findings"]]))
            if audit.get("llm_validation"):
                display(pd.DataFrame(audit["llm_validation"]))
        if audit.get("llm_raw_summary"):
            display(Markdown("**Необработанное заключение LLM (может содержать неподтверждённые утверждения):**\n\n" + audit["llm_raw_summary"]))
        display(Markdown("Ограничения: " + "; ".join(audit.get("limitations", []))))

### patient_001 · live

**Аудит 1. LLM-проверка: нет.**

Подтверждённых нарушений в покрытых проверках не найдено.

Ограничения: Проверяется ограниченный каталог выбранного сценария; отсутствие находок не доказывает клиническую безопасность.; Любой непустой список сопутствующих заболеваний находится за пределами текущих демонстрационных случаев и требует ручной оценки; это не правило о противопоказании антибиотиков при любых заболеваниях.; Связь назначения с источником проверяется по вручную подтверждённому каталогу, а не универсальным доказательством логического следования текста.; Проверка доз покрывает только заранее заданные режимы. eGFR>=90 и АЛТ/АСТ<=40 — консервативные границы демонстрационного набора, не универсальные противопоказания или полная оценка функции органов.; Правило взаимодействий явно покрывает левофлоксацин+амиодарон; полной базы лекарственных взаимодействий нет.; QTc<450 и калий>=3.5 — границы синтетического входного набора; они не доказывают отсутствие риска и не являются полной клинической стратификацией.; КР, инструкция препарата и политики демонстрации имеют отдельные идентификаторы и разную область применимости.; Наблюдения датируются с точностью до дня. При наличии синтетического execution_log его sequence отражает относительный порядок забора мокроты и начала препаратов внутри дня; без журнала этот порядок неизвестен.; Наличие отдельного показателя — ограниченное свидетельство исследования; полнота всех полей анализа и качество образца здесь не валидируются.; Historical отмечает повторяющуюся проблему старой версии; resolved сохраняет исправленную историческую находку. Только open описывает текущую нерешённую проблему.

**Аудит 2. LLM-проверка: да.**

Независимый LLM-аудит: подтверждено 0 замечаний; 0 предположений не подтверждено проверяемыми правилами. Они сохранены отдельно и не изменяют лечение автоматически.

Подтверждённых нарушений в покрытых проверках не найдено.

**Необработанное заключение LLM (может содержать неподтверждённые утверждения):**

Планы лечения соответствуют источникам и данным пациента без выявленных противоречий. Все назначенные исследования и медикаменты соответствуют рекомендациям и доступным данным на момент принятия решений. Нарушений в дозировке, отсутствии необходимых исследований или противоречий в данных пациента не обнаружено.

Ограничения: Проверяется ограниченный каталог выбранного сценария; отсутствие находок не доказывает клиническую безопасность.; Любой непустой список сопутствующих заболеваний находится за пределами текущих демонстрационных случаев и требует ручной оценки; это не правило о противопоказании антибиотиков при любых заболеваниях.; Связь назначения с источником проверяется по вручную подтверждённому каталогу, а не универсальным доказательством логического следования текста.; Проверка доз покрывает только заранее заданные режимы. eGFR>=90 и АЛТ/АСТ<=40 — консервативные границы демонстрационного набора, не универсальные противопоказания или полная оценка функции органов.; Правило взаимодействий явно покрывает левофлоксацин+амиодарон; полной базы лекарственных взаимодействий нет.; QTc<450 и калий>=3.5 — границы синтетического входного набора; они не доказывают отсутствие риска и не являются полной клинической стратификацией.; КР, инструкция препарата и политики демонстрации имеют отдельные идентификаторы и разную область применимости.; Наблюдения датируются с точностью до дня. При наличии синтетического execution_log его sequence отражает относительный порядок забора мокроты и начала препаратов внутри дня; без журнала этот порядок неизвестен.; Наличие отдельного показателя — ограниченное свидетельство исследования; полнота всех полей анализа и качество образца здесь не валидируются.; Historical отмечает повторяющуюся проблему старой версии; resolved сохраняет исправленную историческую находку. Только open описывает текущую нерешённую проблему.; Отсутствует информация о результатах посева мокроты на момент принятия решений в обеих версиях плана (culture_available_at_decision = null). Это не позволяет проверить соответствие антибиотикотерапии данным микробиологического исследования.; Не обнаружено данных о наличии или отсутствии аллергии на бета-лактамные антибиотики в анамнезе пациента, что не позволяет окончательно подтвердить отсутствие риска аллергической реакции на ампициллин.; Не обнаружено данных о наличии или отсутствии сопутствующих заболеваний, которые могли бы потребовать дополнительной коррекции терапии.; Не обнаружено данных о выполнении процедурных согласий (например, на возможные инвазивные исследования).; Не обнаружено данных о выполнении предварительных условий для процедур с контрастом (например, оценка функции почек перед возможным введением контрастных веществ).; Проверка предложений LLM ограничена реализованными фактическими правилами. Утверждения вне этого набора сохраняются как непроверенные и требуют эксперта. Совпадение идентификаторов источников не доказывает произвольное смысловое утверждение; принятые находки используют каноническую формулировку проверенного правила.

### patient_002 · live

**Требуется экспертная проверка.** Неподтверждённые гипотезы и недостаточные данные не считаются чистым аудитом.

**Аудит 1. LLM-проверка: нет.**

Подтверждённых нарушений в покрытых проверках не найдено.

Ограничения: Проверяется ограниченный каталог выбранного сценария; отсутствие находок не доказывает клиническую безопасность.; Любой непустой список сопутствующих заболеваний находится за пределами текущих демонстрационных случаев и требует ручной оценки; это не правило о противопоказании антибиотиков при любых заболеваниях.; Связь назначения с источником проверяется по вручную подтверждённому каталогу, а не универсальным доказательством логического следования текста.; Проверка доз покрывает только заранее заданные режимы. eGFR>=90 и АЛТ/АСТ<=40 — консервативные границы демонстрационного набора, не универсальные противопоказания или полная оценка функции органов.; Правило взаимодействий явно покрывает левофлоксацин+амиодарон; полной базы лекарственных взаимодействий нет.; QTc<450 и калий>=3.5 — границы синтетического входного набора; они не доказывают отсутствие риска и не являются полной клинической стратификацией.; КР, инструкция препарата и политики демонстрации имеют отдельные идентификаторы и разную область применимости.; Наблюдения датируются с точностью до дня. При наличии синтетического execution_log его sequence отражает относительный порядок забора мокроты и начала препаратов внутри дня; без журнала этот порядок неизвестен.; Наличие отдельного показателя — ограниченное свидетельство исследования; полнота всех полей анализа и качество образца здесь не валидируются.; Historical отмечает повторяющуюся проблему старой версии; resolved сохраняет исправленную историческую находку. Только open описывает текущую нерешённую проблему.

**Аудит 2. LLM-проверка: да.**

Независимый LLM-аудит: подтверждено 0 замечаний; 2 предположений не подтверждено проверяемыми правилами. Они сохранены отдельно и не изменяют лечение автоматически.

Подтверждённых нарушений в покрытых проверках не найдено.

**Неподтверждённые предположения LLM — отдельная экспертная оценка**

,Код,Версия,Гипотеза,Заявленное основание,Источники
0,required_ecg_missing,1,На момент принятия решения в версии 1 отсутств...,В patient_states отсутствуют данные о выполнен...,cap-ecg
1,required_biochemistry_missing,1,На момент принятия решения в версии 1 отсутств...,В patient_states отсутствуют данные о выполнен...,cap-biochemistry

,index,code,plan_version,action_id,proposed,decision,accepted,reason,coverage_limitation
0,0,required_ecg_missing,1,None,"{'code': 'required_ecg_missing', 'severity': '...",unverified,False,"Нет фактической находки с теми же code, plan_v...",Проверка предложений LLM ограничена реализован...
1,1,required_biochemistry_missing,1,None,"{'code': 'required_biochemistry_missing', 'sev...",unverified,False,"Нет фактической находки с теми же code, plan_v...",Проверка предложений LLM ограничена реализован...

**Необработанное заключение LLM (может содержать неподтверждённые утверждения):**

Планы лечения соответствуют источникам и данным пациента без критических нарушений. Обнаружено одно нарушение средней степени тяжести в версии 1, связанное с отсутствием выполнения обязательных исследований (ЭКГ и биохимического анализа крови) на момент принятия решения. Нарушение было устранено в последующих версиях планов. Также отмечается отсутствие данных о посеве мокроты с чувствительностью на момент принятия решений в обеих версиях, но это не является нарушением, так как посев ещё не был готов.

Ограничения: Проверяется ограниченный каталог выбранного сценария; отсутствие находок не доказывает клиническую безопасность.; Любой непустой список сопутствующих заболеваний находится за пределами текущих демонстрационных случаев и требует ручной оценки; это не правило о противопоказании антибиотиков при любых заболеваниях.; Связь назначения с источником проверяется по вручную подтверждённому каталогу, а не универсальным доказательством логического следования текста.; Проверка доз покрывает только заранее заданные режимы. eGFR>=90 и АЛТ/АСТ<=40 — консервативные границы демонстрационного набора, не универсальные противопоказания или полная оценка функции органов.; Правило взаимодействий явно покрывает левофлоксацин+амиодарон; полной базы лекарственных взаимодействий нет.; QTc<450 и калий>=3.5 — границы синтетического входного набора; они не доказывают отсутствие риска и не являются полной клинической стратификацией.; КР, инструкция препарата и политики демонстрации имеют отдельные идентификаторы и разную область применимости.; Наблюдения датируются с точностью до дня. При наличии синтетического execution_log его sequence отражает относительный порядок забора мокроты и начала препаратов внутри дня; без журнала этот порядок неизвестен.; Наличие отдельного показателя — ограниченное свидетельство исследования; полнота всех полей анализа и качество образца здесь не валидируются.; Historical отмечает повторяющуюся проблему старой версии; resolved сохраняет исправленную историческую находку. Только open описывает текущую нерешённую проблему.; Отсутствие данных о посеве мокроты с чувствительностью на момент принятия решений в обеих версиях не является нарушением, так как посев ещё не был готов (culture_available_at_decision = null).; Данные о выполнении ЭКГ и биохимического анализа крови отсутствуют в patient_states только на день 0, но в версии 2 эти исследования включены в планы и могут быть выполнены в последующие дни.; Недоступность данных о культуральной резистентности на момент принятия решений не позволяет проверить соответствие антибиотикотерапии результатам посева.; Недостаточно данных для проверки выполнения согласия на процедуры и предварительных условий для исследований с контрастом.; Проверка предложений LLM ограничена реализованными фактическими правилами. Утверждения вне этого набора сохраняются как непроверенные и требуют эксперта. Совпадение идентификаторов источников не доказывает произвольное смысловое утверждение; принятые находки используют каноническую формулировку проверенного правила.

### patient_003 · live

**Требуется экспертная проверка.** Неподтверждённые гипотезы и недостаточные данные не считаются чистым аудитом.

**Аудит 1. LLM-проверка: нет.**

Подтверждённых нарушений в покрытых проверках не найдено.

Ограничения: Проверяется ограниченный каталог выбранного сценария; отсутствие находок не доказывает клиническую безопасность.; Любой непустой список сопутствующих заболеваний находится за пределами текущих демонстрационных случаев и требует ручной оценки; это не правило о противопоказании антибиотиков при любых заболеваниях.; Связь назначения с источником проверяется по вручную подтверждённому каталогу, а не универсальным доказательством логического следования текста.; Проверка доз покрывает только заранее заданные режимы. eGFR>=90 и АЛТ/АСТ<=40 — консервативные границы демонстрационного набора, не универсальные противопоказания или полная оценка функции органов.; Правило взаимодействий явно покрывает левофлоксацин+амиодарон; полной базы лекарственных взаимодействий нет.; QTc<450 и калий>=3.5 — границы синтетического входного набора; они не доказывают отсутствие риска и не являются полной клинической стратификацией.; КР, инструкция препарата и политики демонстрации имеют отдельные идентификаторы и разную область применимости.; Наблюдения датируются с точностью до дня. При наличии синтетического execution_log его sequence отражает относительный порядок забора мокроты и начала препаратов внутри дня; без журнала этот порядок неизвестен.; Наличие отдельного показателя — ограниченное свидетельство исследования; полнота всех полей анализа и качество образца здесь не валидируются.; Historical отмечает повторяющуюся проблему старой версии; resolved сохраняет исправленную историческую находку. Только open описывает текущую нерешённую проблему.

**Аудит 2. LLM-проверка: да.**

Независимый LLM-аудит: подтверждено 0 замечаний; 2 предположений не подтверждено проверяемыми правилами. Они сохранены отдельно и не изменяют лечение автоматически.

Подтверждённых нарушений в покрытых проверках не найдено.

**Неподтверждённые предположения LLM — отдельная экспертная оценка**

,Код,Версия,Гипотеза,Заявленное основание,Источники
0,known_culture_resistance,2,На момент принятия решения о назначении левофл...,Haemophilus influenzae с устойчивостью к ампиц...,"cap-culture-interpretation, cap-sputum-culture"
1,required_sputum_culture_missing,1,В версии 1 отсутствует подтверждение сбора мок...,Сбор мокроты зарегистрирован в журнале исполне...,cap-sputum-before-antibiotics

,index,code,plan_version,action_id,proposed,decision,accepted,reason,coverage_limitation
0,0,known_culture_resistance,2,v2:levofloxacin_iv,"{'code': 'known_culture_resistance', 'severity...",unverified,False,"Нет фактической находки с теми же code, plan_v...",Проверка предложений LLM ограничена реализован...
1,1,required_sputum_culture_missing,1,None,"{'code': 'required_sputum_culture_missing', 's...",unverified,False,"Нет фактической находки с теми же code, plan_v...",Проверка предложений LLM ограничена реализован...

**Необработанное заключение LLM (может содержать неподтверждённые утверждения):**

В версии 1 план соответствовал источникам и данным пациента, за исключением отсутствия подтверждения сбора мокроты до начала антибиотикотерапии. В версии 2 выявлено нарушение из-за известной резистентности Haemophilus influenzae к ампициллину на момент принятия решения о назначении левофлоксацина. Также отмечается отсутствие данных о согласии на процедуры и предварительной оценке функции почек для возможных исследований с контрастом, хотя сами процедуры не выполнялись.

Ограничения: Проверяется ограниченный каталог выбранного сценария; отсутствие находок не доказывает клиническую безопасность.; Любой непустой список сопутствующих заболеваний находится за пределами текущих демонстрационных случаев и требует ручной оценки; это не правило о противопоказании антибиотиков при любых заболеваниях.; Связь назначения с источником проверяется по вручную подтверждённому каталогу, а не универсальным доказательством логического следования текста.; Проверка доз покрывает только заранее заданные режимы. eGFR>=90 и АЛТ/АСТ<=40 — консервативные границы демонстрационного набора, не универсальные противопоказания или полная оценка функции органов.; Правило взаимодействий явно покрывает левофлоксацин+амиодарон; полной базы лекарственных взаимодействий нет.; QTc<450 и калий>=3.5 — границы синтетического входного набора; они не доказывают отсутствие риска и не являются полной клинической стратификацией.; КР, инструкция препарата и политики демонстрации имеют отдельные идентификаторы и разную область применимости.; Наблюдения датируются с точностью до дня. При наличии синтетического execution_log его sequence отражает относительный порядок забора мокроты и начала препаратов внутри дня; без журнала этот порядок неизвестен.; Наличие отдельного показателя — ограниченное свидетельство исследования; полнота всех полей анализа и качество образца здесь не валидируются.; Historical отмечает повторяющуюся проблему старой версии; resolved сохраняет исправленную историческую находку. Только open описывает текущую нерешённую проблему.; Отсутствие данных о согласии на процедуры и предварительной оценке функции почек для возможных исследований с контрастом не подтверждает нарушений, так как сами процедуры не выполнялись.; Недостаточно данных о факторах риска инфицирования полирезистентными возбудителями, кроме резистентности к ампициллину.; Недостаточно данных о наличии аллергий на бета-лактамные антибиотики и фторхинолоны, что не позволяет проверить соответствие требований каталога.; Проверка предложений LLM ограничена реализованными фактическими правилами. Утверждения вне этого набора сохраняются как непроверенные и требуют эксперта. Совпадение идентификаторов источников не доказывает произвольное смысловое утверждение; принятые находки используют каноническую формулировку проверенного правила.

## Проверяемые источники

Ниже приведены использованные локальные фрагменты. Номер страницы и раздел относятся к зафиксированной редакции документа; технический ID не заменяет номер пункта КР.

In [5]:
chunks = []
for name in ["document_chunks.json", "chunks.json", "chunks.jsonl", "guideline_chunks.json", "guideline_chunks.jsonl", "supplemental_chunks.json", "policies.json"]:
    path = ROOT / "data" / name
    if path.exists():
        data = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()] if path.suffix == ".jsonl" else load(path)
        records = data.get("chunks", data.get("documents", list(data.values()))) if isinstance(data, dict) else data
        role = "Автоматический фрагмент PDF" if name == "document_chunks.json" else "Опорная выдержка для проверки" if name == "chunks.json" else "Дополнительный источник"
        chunks.extend({**item, "display_role": role} for item in records)
used = {e for _, t in traces for p in t["plans"] for a in p["actions"] for e in a["evidence_ids"]}
used |= {e for _, t in traces for audit in t.get("audits", []) for f in audit["findings"] for e in f["evidence_ids"]}
used |= {e for _, t in traces for audit in t.get("audits", []) for f in audit.get("unverified_findings", []) for e in f["evidence_ids"]}
for chunk in chunks:
    identifier = chunk.get("id", chunk.get("chunk_id"))
    if identifier in used:
        page = chunk.get("page", chunk.get("pdf_page", chunk.get("pages", "—")))
        section = chunk.get("section", chunk.get("section_title", "—"))
        url = chunk.get("source_url", chunk.get("url")) or chunk.get("source", {}).get("url")
        if url and isinstance(page, int) and ".pdf" in url.lower():
            url = url.split("#", 1)[0] + f"#page={page}"
        link = f"\n\n[Открыть источник]({url})" if url else ""
        display(Markdown(f"**{identifier} · {chunk['display_role']} · {section} · страница {page or '—'}**\n\n{chunk.get('text', chunk.get('content', ''))}{link}"))
missing = used - {c.get("id", c.get("chunk_id")) for c in chunks}
if missing:
    display(Markdown("**Не найдены локальные фрагменты:** " + ", ".join(sorted(missing))))

**cap-vitals · Опорная выдержка для проверки · 2.2 · страница 13**

У всех пациентов с ВП рекомендуется провести общий осмотр, измерить показатели жизненно-важных функций(частотой дыхательных движений (ЧДД), частота сердечных сокращений (ЧСС), артериальное давление (АД),температура тела) и выполнить детальное обследование грудной клетки как неотъемлемых компонентов установлениядиагноза, оценки тяжести ВП и прогноза [1].

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=13)

**cap-pulse-oximetry · Опорная выдержка для проверки · 2.2 · страница 13**

Всем пациентам с ВП рекомендуется пульсоксиметрия с измерением SpO для выявления ДН и оценки выраженностигипоксемии [2, 93].

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=13)

**cap-cbc · Опорная выдержка для проверки · 2.3 · страница 14**

Всем пациентам с ВП рекомендуется выполнение общего (клинического) анализа крови с определением уровняэритроцитов, гематокрита, лейкоцитов, тромбоцитов, лейкоцитарной формулы с целью установления диагноза, оценкитяжести ВП и прогноза [1].

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=14)

**cap-biochemistry · Опорная выдержка для проверки · 2.3 · страница 14**

Всем госпитализированным пациентам с ВП рекомендуется выполнить анализ крови биохимическийобщетерапевтический (мочевина, креатинин, общий билирубин, глюкоза, альбумин, исследование уровня натрия, калия,хлоридов, определение активности аспартатаминотрансферазы, активности аланинамино-трансферазы в крови) с цельюопределения тяжести ВП и прогноза, выявления декомпенсации сопутствующей патологии, назначения и коррекциифармакотерапии [1].

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=14)

**cap-crp · Опорная выдержка для проверки · 2.3 · страница 14**

Всем госпитализированным пациентам с ВП рекомендуется исследование уровня
С-реактивного белка (СРБ) в сыворотке крови с целью установления диагноза, оценки тяжести ВП и прогноза [50, 259].

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=14)

**cap-sputum-culture · Опорная выдержка для проверки · 2.3.1 · страница 15**

Всем госпитализированным пациентам с ВП рекомендуется микроскопическое исследование нативного и окрашенногопрепарата мокроты (по Граму) и микробиологическое (культуральное) исследование мокроты (ТА у пациентов,находящихся на ИВЛ) на аэробные и факультативно-анаэробные микроорганизмы –для принятия решения о выборестартового режима эмпирической АБТ, необходимости её коррекции и/или ранней деэскалации [1, 262].

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=15)

**cap-sputum-before-antibiotics · Опорная выдержка для проверки · 2.3.1, комментарий · страница 16**

Образец свободно отделяемой мокроты должен быть получен у всех пациентов с продуктивным кашлем в как можноболее ранние сроки с момента госпитализации и до начала АБТ. При непродуктивном кашле может быть предпринятапопытка получения индуцированной мокроты (см. Приложение). В случае интубации и начала ИВЛ для культуральногоисследования вместо мокроты должен быть получен ТА [19, 33, 58].

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=16)

**cap-culture-interpretation · Опорная выдержка для проверки · 2.3.1, комментарий · страница 16**

Интерпретация результатов культурального исследования мокроты и ТА должна проводиться с учетоммикроскопического исследования окрашенного по Граму препарата мокроты и клинических данных, так как данныеобразцы могут быть контаминированы микрофлорой полости рта и верхних дыхательных путей [60].

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=16)

**cap-ecg · Опорная выдержка для проверки · 2.4 · страница 19**

Всем госпитализированным пациентам с ВП рекомендуется ЭКГ в стандартных отведениях для исключенияосложнений ВП, выявления сопутствующих заболеваний и выбора безопасного режима АБТ [1].
Уровень убедительности рекомендаций С (уровень достоверности доказательств – 5)
Комментарии: Данное исследование не несет в себе какой-либо специфической информации при ВП. Однако, в настоящеевремя известно, что ВП помимо декомпенсации хронических сопутствующих заболеваний увеличивает риск развитиянарушений ритма и острого коронарного синдрома, своевременное выявление которых значимо влияет на прогноз [80].Кроме того, определенные изменения на ЭКГ (например, удлинение интервала QT, наличие синдрома ранней реполяризациижелудочков) повышает кардиотоксичность ряда АБП системного действия.

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=19)

**cap-parenteral · Опорная выдержка для проверки · 3.2.1 · страница 24**

АБТ ВП у госпитализированных пациентов рекомендуется начинать с парентеральных ЛФ (таблица 8); при ТВПрекомендуется начинать с внутривенного введения АБП системного действия с целью обеспечения высокой ипредсказуемой биодоступности ЛС [1].
Уровень убедительности рекомендаций С (уровень достоверности доказательств – 5)
Комментарии: У госпитализированных пациентов подразумевается более тяжелое течение ВП, поэтому целесообразноначинать терапию с парентеральных АБП системного действия. Стартовая АБТ тяжелой ВП предполагаетвнутривенное введение АБП системного действия, т.к. данный путь доставки обеспечивает наиболее высокую ипредсказуемую биодоступность, не зависящую от полноты и скорости всасывания препаратов в ЖКТ [32, 33]. Вдальнейшем по мере клинической стабилизации возможет перевод пациента на пероральный прием АБП системногодействия в рамках концепции ступенчатой терапии.
При нетяжелом течении ВП в случае госпитализации пациента по немедицинским показаниям допускается сразуназначение АБП системного действия внутрь [117].

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=24)

**cap-empiric · Опорная выдержка для проверки · 3.2.1 · страница 24**

Пациентам с ВП без значимых сопутствующих заболеваний и других факторов риска инфицирования редкими и/илиПРВ в качестве препаратов выбора рекомендуются ампициллин**, амоксициллин+клавулановая кислота** илиампициллин+сульбактам**, альтернативы – РХ [1, 12].

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=24)

**cap-beta-allergy · Опорная выдержка для проверки · 3.2.1, комментарий · страница 25**

Комментарии: Наиболее частыми “типичными” бактериальными возбудителями ВП у данной категории пациентовявляются S. pneumoniae и H. influenzae, в отношении которых ампициллин** сохраняет достаточную активность [20]. Всвязи с этим рутинное назначение АБП системного действия более широкого спектра пациентам первой группынецелесообразно. Комбинации пенициллинов, включая комбинации с ингибиторами бета-лактамаз, могут назначаться принизкой приверженности терапии ампициллином**, который требует 4-х кратного введения в сутки (см. раздел“Рекомендации по режиму дозирования АБП”), РХ - при невозможности назначить пенициллины (индивидуальнаянепереносимость, аллергические реакции немедленного типа на бета-лактамные АБП: пенициллины и/или другие бета-лактамные АБП в анамнезе).

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=25)

**cap-inpatient-table · Опорная выдержка для проверки · 3.2.1, таблица 8 · страница 25**

Таблица 8. Антибактериальная терапия нетяжелой ВП в стационаре
Группа Наиболее частыевозбудители Препараты выбора Альтернатива
Нетяжелая ВП у пациентов без сопутствующих заболеваний, непринимавших за последние 3 мес АБП системного действия ≥2дней и не имеющих других факторов риска
S. pneumoniaeM. pneumoniaeC. pneumoniaeH. influenzaeРеспираторныевирусы
Ампициллин** в/в, в/мИЛИАмоксициллин+клавулановаякислота**, в/в, в/мИЛИАмпициллин+сульбактам**, в/в, в/м
РХ (левофлоксацин**,моксифлоксацин**) в/в

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=25)

**cap-reassess-72h · Опорная выдержка для проверки · 3.2.1 · страница 28**

Всем пациентам с ВП через 48-72 ч после начала лечения рекомендуется оценка эффективности и безопасности ипересмотр стартового режима АБТ для своевременного пересмотра тактики лечения c возможной его деэскалацией [1,59].
Уровень убедительности рекомендаций С (Уровень достверности доказательств – 5)
Комментарии: Как и при лечении амбулаторных пациентов, основными критериями эффективности АБТ в эти срокиявляются снижение температуры, уменьшение выраженности интоксикационного синдрома и основных клиническихсимптомов и признаков ВП, ДН, при ТВП - проявлений ПОН [1,2, 93, 193].

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=28)

**cap-treatment-failure · Опорная выдержка для проверки · 3.2.1, комментарий · страница 28**

Если у пациента сохраняется лихорадка и интоксикационный синдром, прогрессируют симптомы и признаки ВП илиразвиваются осложнения, АБТ следует расценивать как неэффективную. В этом случае, а также появлении НЛР,требующих отмены АБП системного действия, необходимо пересмотреть тактику лечения, повторно оценить тяжестьВП и целесообразность перевода в ОРИТ.

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=28)

**cap-crp-dynamics · Опорная выдержка для проверки · 3.2.1, комментарий · страница 28**

Из лабораторных тестов целесообразно определение СРБ в сыворотке крови на
3-4-й день начала терапии. Повышение концентрации СРБ или снижение менее чем на 50% через свидетельствует онеэффективности терапии и неблагоприятном прогнозе [52,55].

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=28)

**cap-oral-switch-1 · Опорная выдержка для проверки · 3.2.1, критерии клинической стабильности (начало) · страница 28**

Всем госпитализированным пациентам с ВП рекомендуется перевод с парентерального на пероральный прием АБПсистемного действия при достижении критериев клинической стабильности (должны присутствовать все нижеперечисленные) [1, 12. 59, 110]:
- cнижение температуры тела до субфебрильных цифр (<37,8ºC) при двух измерениях с интервалом 8 ч;
- отсутствие нарушений сознания;

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=28)

**cap-oral-switch-2 · Опорная выдержка для проверки · 3.2.1, критерии клинической стабильности (продолжение) · страница 29**

- частота дыхания < 24/мин;
- частота сердечных сокращений < 100/мин;
- систолическое АД > 90 мм рт ст;
- SpO > 90% или PaO  > 60 мм рт ст (артериальная кровь);
- отсутствие нарушений всасывания в ЖКТ.
с целью сокращения длительности парентеральной АБТ и сроков пребывания в стационаре, уменьшения риска осложненийи стоимости лечения.

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=29)

**cap-fluoroquinolones · Опорная выдержка для проверки · Приложение А3, фторхинолоны · страница 62**

Среди препаратов данной группы наибольшее значение при ВП имеют левофлоксацин** и моксифлоксацин**, которыедействуют практически на все ключевые возбудители ВП, включая ПРП, большинство штаммов H. influenzae; ихактивность в отношении M. pneumoniae, C. pneumoniae и S.aureus существенно выше фторхинолонов предыдущегопоколения (ципрофлоксацин**, офлоксацин** и др.) [ 91, 92].

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=62)

**cap-qt · Опорная выдержка для проверки · Приложение А3, препараты других групп · страница 63**

Среди тетрациклинов наиболее приемлемым, учитывая фармакокинетические особенности, переносимость и удобствоприменения является доксициклин**. Он характеризуется хорошей активностью в отношении M. pneumoniae, C.pneumoniae и низким уровнем вторичной резистентности H. influenzae в РФ. Высокая частота выделениятетрациклинорезистентных штаммов S. pneumoniae в России не позволяет рассматривать его в качестве препарата выборадля эмпирической терапии ВП. Для госпитализированных пациентов при наличии противопоказаний к назначению b-лактамов и отсутствии других терапевтических опции может рассматриваться тигециклин; он же, учитывая наличиеактивности против L. pneumophila, M. pneumoniae, C. pneumoniae, может назначаться вместе с b-лактамными АБ приТВП и удлиненном интервале QTc, т.к. в данном случае применение макролидов и фторхинолонов противопоказано.

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=63)

**cap-dose-scope · Опорная выдержка для проверки · Приложение А3, режимы дозирования АМП · страница 64**

Режимы дозирования АМП (нормальная функция печени и почек)

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=64)

**cap-dose-ampicillin · Опорная выдержка для проверки · Приложение А3, режимы дозирования АМП · страница 64**

Ампициллин** 2,0 г в/в, в/м каждые 6 ч

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=64)

**cap-dose-levofloxacin · Опорная выдержка для проверки · Приложение А3, режимы дозирования АМП · страница 64**

Левофлоксацин** 0,5 г каждые 12 ч внутрь или в/в или 0,75 г каждые 24 ч внутрь

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=64)

**cap-hydration · Опорная выдержка для проверки · Приложение В, информация для пациентов · страница 68**

При пневмонии рекомендуется также временно ограничить чрезмерную физическую нагрузку и пить достаточноеколичество жидкости.

[Открыть источник](https://spulmo.ru/upload/KR-vnebolnichnaya-pnevmoniya-u-vzroslyh-2024.pdf#page=68)

## Проверочные прогоны

Внесённые дефекты проверяют обнаружение конкретных ошибок на копиях эталонных планов. Они отделены от трёх основных случаев. Результаты характеризуют этот набор тестов.

In [6]:
evaluation_files = sorted(path for path in (ROOT / "reports").rglob("evaluation.json") if "development" not in path.relative_to(ROOT / "reports").parts)
if not evaluation_files:
    display(Markdown("Отчёт evaluation.json отсутствует; результаты оценивания здесь не заявляются."))
for path in evaluation_files:
    display(Markdown(f"**{path.relative_to(ROOT)}**"))
    display(load(path))

**reports/evaluation/evaluation.json**

{'mode': 'offline',
 'fault_injection': True,
 'note': 'Базовые планы для мутаций — явно обозначенные офлайн-эталоны. LLM-аудит выполняется независимо в live-примерах дозы и процедурных условий. Это малый демонстрационный набор, не оценка клинической надежности.',
 'rule_detection': {'detected': 9,
  'total': 9,
  'cases': [{'id': 'wrong_dose',
    'expected': 'catalog_parameter_mismatch',
    'detected': True,
    'found_codes': ['catalog_parameter_mismatch']},
   {'id': 'irrelevant_citation',
    'expected': 'citation_support_incomplete',
    'detected': True,
    'found_codes': ['citation_support_incomplete', 'citation_unrelated']},
   {'id': 'invented_citation',
    'expected': 'citation_missing',
    'detected': True,
    'found_codes': ['citation_missing',
     'citation_support_incomplete',
     'citation_unrelated']},
   {'id': 'ignored_allergy',
    'expected': 'beta_lactam_allergy',
    'detected': True,
    'found_codes': ['beta_lactam_allergy']},
   {'id': 'drug_interaction',
    'expected': 'levofloxacin_amiodarone',
    'detected': True,
    'found_codes': ['levofloxacin_amiodarone']},
   {'id': 'ordered_ecg_without_result',
    'expected': 'qtc_unknown',
    'detected': True,
    'found_codes': ['qtc_unknown']},
   {'id': 'ignored_resistance',
    'expected': 'known_culture_resistance',
    'detected': True,
    'found_codes': ['known_culture_resistance']},
   {'id': 'procedure_without_renal_result',
    'expected': 'contrast_renal_precondition_missing',
    'detected': True,
    'found_codes': ['action_outside_catalog',
     'renal_data_missing',
     'procedure_consent_missing',
     'contrast_renal_precondition_missing']},
   {'id': 'procedure_without_consent',
    'expected': 'procedure_consent_missing',
    'detected': True,
    'found_codes': ['action_outside_catalog',
     'renal_data_missing',
     'procedure_consent_missing',
     'contrast_renal_precondition_missing']}],
  'evaluator': 'deterministic_rules',
  'llm_evaluated': False},
 'clean_controls': [{'id': 'patient_001', 'open_findings': 0},
  {'id': 'patient_002', 'open_findings': 0},
  {'id': 'patient_003', 'open_findings': 0}],
 'llm_example': None,
 'llm_procedural_example': None,
 'retrieval': {'queries': 10,
  'reference_recall_at_5': 0.85,
  'reference_hit_at_5': 0.9,
  'mean_recall_at_5': 0.85,
  'hit_at_5': 0.9,
  'note': 'Покрытие эталонных фрагментов текстом только top-5 найденных чанков, без соседей. mean_recall_at_5 и hit_at_5 — совместимые псевдонимы reference-метрик; это не recall идентификаторов автоматического индекса.',
  'results': [{'query': 'Какой стартовый антибиотик рекомендован при нетяжёлой внебольничной пневмонии в стационаре без значимых сопутствующих заболеваний?',
    'expected_ids': ['cap-empiric', 'cap-inpatient-table'],
    'actual_ids': ['ru-cap-654_2-2024:p024:0-4026:4e71fb2da3',
     'ru-cap-654_2-2024:p066:0-1060:ec683a8da8',
     'ru-cap-654_2-2024:p025:2108-4644:797d49dcf6',
     'demo-policy-comorbidity-scope',
     'ru-cap-654_2-2024:p022:0-4097:01c876882b'],
    'covered_reference_ids': ['cap-antibiotic-timing',
     'cap-empiric',
     'cap-inpatient-table',
     'cap-no-routine-combination',
     'cap-parenteral',
     'cap-risk-stratification'],
    'reference_recall_at_5': 1.0,
    'reference_hit_at_5': True},
   {'query': 'Чем заменить пенициллины при аллергической реакции немедленного типа на бета-лактамные антибиотики?',
    'expected_ids': ['cap-beta-allergy'],
    'actual_ids': ['ru-cap-654_2-2024:p025:0-2661:688843605a',
     'ru-cap-654_2-2024:p021:2262-4272:32d319cb31',
     'ru-cap-654_2-2024:p062:0-3752:c3d496b013',
     'ru-cap-654_2-2024:p061:0-2459:45901d1689',
     'ru-cap-654_2-2024:p027:0-4502:a4f2ff81ef'],
    'covered_reference_ids': ['cap-beta-allergy',
     'cap-fluoroquinolones',
     'cap-no-routine-combination'],
    'reference_recall_at_5': 1.0,
    'reference_hit_at_5': True},
   {'query': 'Какая доза и кратность внутривенного левофлоксацина указана в рекомендациях?',
    'expected_ids': ['cap-dose-levofloxacin'],
    'actual_ids': ['ru-cap-654_2-2024:p021:2262-4272:32d319cb31',
     'drug-levo-allergy',
     'ru-cap-654_2-2024:p030:0-2627:c050a56cc0',
     'drug-levo-qt',
     'ru-cap-654_2-2024:p064:0-2672:6c081e3cc5'],
    'covered_reference_ids': ['cap-dose-amoxiclav',
     'cap-dose-ampicillin',
     'cap-dose-levofloxacin',
     'cap-dose-scope'],
    'reference_recall_at_5': 1.0,
    'reference_hit_at_5': True},
   {'query': 'Какие биохимические показатели крови, функции почек и печени нужно исследовать госпитализированному пациенту?',
    'expected_ids': ['cap-biochemistry'],
    'actual_ids': ['ru-cap-654_2-2024:p042:0-2465:1e0a96f285',
     'demo-policy-renal-contrast',
     'ru-cap-654_2-2024:p065:0-2919:6f59368c7a',
     'ru-cap-654_2-2024:p014:0-3772:2de1772cc1',
     'ru-cap-654_2-2024:p013:0-3143:3cd492287a'],
    'covered_reference_ids': ['cap-biochemistry',
     'cap-cbc',
     'cap-crp',
     'cap-history',
     'cap-pulse-oximetry',
     'cap-vitals'],
    'reference_recall_at_5': 1.0,
    'reference_hit_at_5': True},
   {'query': 'Когда следует получить мокроту для посева относительно начала антибактериальной терапии?',
    'expected_ids': ['cap-sputum-before-antibiotics'],
    'actual_ids': ['ru-cap-654_2-2024:p028:0-4241:d7d462548a',
     'ru-cap-654_2-2024:p029:0-3728:4f7fa618b9',
     'ru-cap-654_2-2024:p023:0-4029:5d384f2f54',
     'ru-cap-654_2-2024:p063:0-3086:8880e573e4',
     'ru-cap-654_2-2024:p022:0-4097:01c876882b'],
    'covered_reference_ids': ['cap-crp-dynamics',
     'cap-culture-review',
     'cap-oral-switch-1',
     'cap-oral-switch-2',
     'cap-qt',
     'cap-reassess-72h',
     'cap-treatment-failure'],
    'reference_recall_at_5': 0.0,
    'reference_hit_at_5': False},
   {'query': 'Для чего госпитализированному пациенту с пневмонией делать ЭКГ и оценивать интервал QT?',
    'expected_ids': ['cap-ecg'],
    'actual_ids': ['ru-cap-654_2-2024:p019:0-4458:8f446936a7',
     'ru-cap-654_2-2024:p038:0-2557:4b7dbf1473',
     'ru-cap-654_2-2024:p063:0-3086:8880e573e4',
     'ru-cap-654_2-2024:p038:2087-4358:59092084cc',
     'ru-cap-654_2-2024:p042:1892-4146:a7798ef9f0'],
    'covered_reference_ids': ['cap-ecg', 'cap-qt'],
    'reference_recall_at_5': 1.0,
    'reference_hit_at_5': True},
   {'query': 'Как оценивать эффективность и безопасность стартовой антибиотикотерапии через 48–72 часа?',
    'expected_ids': ['cap-reassess-72h'],
    'actual_ids': ['ru-cap-654_2-2024:p042:1892-4146:a7798ef9f0',
     'ru-cap-654_2-2024:p022:0-4097:01c876882b',
     'ru-cap-654_2-2024:p028:0-4241:d7d462548a',
     'ru-cap-654_2-2024:p029:0-3728:4f7fa618b9',
     'ru-cap-654_2-2024:p026:0-4075:caa06c3d59'],
    'covered_reference_ids': ['cap-crp-dynamics',
     'cap-culture-review',
     'cap-oral-switch-1',
     'cap-oral-switch-2',
     'cap-reassess-72h',
     'cap-treatment-failure'],
    'reference_recall_at_5': 1.0,
    'reference_hit_at_5': True},
   {'query': 'Как использовать результаты микробиологических исследований для пересмотра лечения при его неэффективности?',
    'expected_ids': ['cap-culture-review', 'cap-etiotropic'],
    'actual_ids': ['ru-cap-654_2-2024:p028:0-4241:d7d462548a',
     'ru-cap-654_2-2024:p016:0-4195:4320e0bb09',
     'ru-cap-654_2-2024:p040:0-3542:9cc6025258',
     'ru-cap-654_2-2024:p022:0-4097:01c876882b',
     'ru-cap-654_2-2024:p060:0-3794:8f859f250a'],
    'covered_reference_ids': ['cap-crp-dynamics',
     'cap-culture-interpretation',
     'cap-culture-review',
     'cap-oral-switch-1',
     'cap-reassess-72h',
     'cap-sputum-before-antibiotics',
     'cap-treatment-failure'],
    'reference_recall_at_5': 0.5,
    'reference_hit_at_5': True},
   {'query': 'Какие критерии клинической стабильности должны присутствовать для перевода антибиотика с парентерального на пероральный приём?',
    'expected_ids': ['cap-oral-switch-1', 'cap-oral-switch-2'],
    'actual_ids': ['ru-cap-654_2-2024:p028:0-4241:d7d462548a',
     'ru-cap-654_2-2024:p066:0-1060:ec683a8da8',
     'ru-cap-654_2-2024:p043:0-2306:fa35edce95',
     'ru-cap-654_2-2024:p029:0-3728:4f7fa618b9',
     'ru-cap-654_2-2024:p039:0-3394:a8dbc6b9c8'],
    'covered_reference_ids': ['cap-crp-dynamics',
     'cap-culture-review',
     'cap-oral-switch-1',
     'cap-oral-switch-2',
     'cap-reassess-72h',
     'cap-treatment-failure'],
    'reference_recall_at_5': 1.0,
    'reference_hit_at_5': True},
   {'query': 'Какие рекомендации даны пациенту с пневмонией по жидкости и физической нагрузке?',
    'expected_ids': ['cap-hydration'],
    'actual_ids': ['ru-cap-654_2-2024:p068:2439-4705:ebb720317e',
     'ru-cap-654_2-2024:p036:0-2824:11294208ca',
     'ru-cap-654_2-2024:p023:0-4029:5d384f2f54',
     'ru-cap-654_2-2024:p043:0-2306:fa35edce95',
     'ru-cap-654_2-2024:p018:0-3966:c09e0315a8'],
    'covered_reference_ids': ['cap-chest-xray', 'cap-hydration'],
    'reference_recall_at_5': 1.0,
    'reference_hit_at_5': True}]},
 'usage': {'api_attempts': 0}}

**reports/evaluation_live/evaluation.json**

{'mode': 'live',
 'fault_injection': True,
 'note': 'Базовые планы для мутаций — явно обозначенные офлайн-эталоны. LLM-аудит выполняется независимо в live-примерах дозы и процедурных условий. Это малый демонстрационный набор, не оценка клинической надежности.',
 'rule_detection': {'detected': 9,
  'total': 9,
  'cases': [{'id': 'wrong_dose',
    'expected': 'catalog_parameter_mismatch',
    'detected': True,
    'found_codes': ['catalog_parameter_mismatch']},
   {'id': 'irrelevant_citation',
    'expected': 'citation_support_incomplete',
    'detected': True,
    'found_codes': ['citation_support_incomplete', 'citation_unrelated']},
   {'id': 'invented_citation',
    'expected': 'citation_missing',
    'detected': True,
    'found_codes': ['citation_missing',
     'citation_support_incomplete',
     'citation_unrelated']},
   {'id': 'ignored_allergy',
    'expected': 'beta_lactam_allergy',
    'detected': True,
    'found_codes': ['beta_lactam_allergy']},
   {'id': 'drug_interaction',
    'expected': 'levofloxacin_amiodarone',
    'detected': True,
    'found_codes': ['levofloxacin_amiodarone']},
   {'id': 'ordered_ecg_without_result',
    'expected': 'qtc_unknown',
    'detected': True,
    'found_codes': ['qtc_unknown']},
   {'id': 'ignored_resistance',
    'expected': 'known_culture_resistance',
    'detected': True,
    'found_codes': ['known_culture_resistance']},
   {'id': 'procedure_without_renal_result',
    'expected': 'contrast_renal_precondition_missing',
    'detected': True,
    'found_codes': ['action_outside_catalog',
     'renal_data_missing',
     'procedure_consent_missing',
     'contrast_renal_precondition_missing']},
   {'id': 'procedure_without_consent',
    'expected': 'procedure_consent_missing',
    'detected': True,
    'found_codes': ['action_outside_catalog',
     'renal_data_missing',
     'procedure_consent_missing',
     'contrast_renal_precondition_missing']}],
  'evaluator': 'deterministic_rules',
  'llm_evaluated': False},
 'clean_controls': [{'id': 'patient_001', 'open_findings': 0},
  {'id': 'patient_002', 'open_findings': 0},
  {'id': 'patient_003', 'open_findings': 0}],
 'llm_example': {'llm_detected_wrong_dose': False,
  'verified_wrong_dose_detected': False,
  'evaluated_faults': 1,
  'fault_id': 'wrong_dose',
  'note': 'Raw LLM detection оценивает исходный ответ модели. Rule verification подтверждает цель и нормализует текст; её результат не засчитывается как самостоятельное обнаружение LLM. Процедурные цели проверяются в отдельном примере; остальные дефекты — только правилами.',
  'before': {'raw_llm': {'target_open_detected': False,
    'target_resolved_detected': False,
    'open_critical': 0,
    'findings': [{'code': 'catalog_parameter_mismatch',
      'severity': 'critical',
      'category': 'clinical',
      'plan_version': 1,
      'action_id': 'v1:ampicillin_iv',
      'message': 'Назначенная доза ампициллина (999 г) не соответствует параметрам source_catalog (должно быть 2,0 г).',
      'evidence_ids': ['cap-dose-ampicillin'],
      'patient_evidence': 'Данные пациента: возраст 52 года, мужской пол, диагноз внебольничная пневмония, нетяжёлое течение, отсутствие аллергий и сопутствующих заболеваний.',
      'recommendation': 'Скорректировать дозу ампициллина до 2,0 г в соответствии с source_catalog.',
      'origin': 'llm',
      'status': 'historical'}]},
   'rule_verification': {'target_open_confirmed': True,
    'target_resolved_confirmed': False,
    'accepted_findings': 1,
    'unverified_findings': 0,
    'verified_open_critical': 1},
   'rule_audit': {'target_open_detected': True,
    'target_resolved_detected': False,
    'open_critical': 1}},
  'after': {'raw_llm': {'target_open_detected': False,
    'target_resolved_detected': True,
    'open_critical': 0,
    'findings': [{'code': 'catalog_parameter_mismatch',
      'severity': 'critical',
      'category': 'clinical',
      'plan_version': 1,
      'action_id': 'v1:ampicillin_iv',
      'message': 'Доза ампициллина указана как 999 г, что не соответствует источникам (должно быть 2,0 г).',
      'evidence_ids': ['cap-dose-ampicillin'],
      'patient_evidence': 'Данные пациента: возраст 52 года, нетяжёлая пневмония, нормальная функция почек (eGFR = 99 мл/мин/1.73 м²), отсутствие аллергий.',
      'recommendation': 'Исправить дозу ампициллина на 2,0 г в соответствии с источниками.',
      'origin': 'llm',
      'status': 'resolved'}]},
   'rule_verification': {'target_open_confirmed': False,
    'target_resolved_confirmed': True,
    'accepted_findings': 1,
    'unverified_findings': 0,
    'verified_open_critical': 0},
   'rule_audit': {'target_open_detected': False,
    'target_resolved_detected': True,
    'open_critical': 0}},
  'repair_applied': True,
  'before_findings': 1,
  'before_verified_findings': 1,
  'before_unverified_findings': 0,
  'after_open_critical': 0,
  'after_verified_open_critical': 0,
  'after_unverified_findings': 0,
  'report': 'fault_llm_before_after.json'},
 'llm_procedural_example': {'targets': [{'code': 'contrast_renal_precondition_missing',
    'plan_version': 1,
    'action_id': 'v1:contrast_ct',
    'raw_llm_detected': True,
    'rule_verified': True,
    'raw_llm_detected_and_verified': True,
    'rule_detected': True},
   {'code': 'procedure_consent_missing',
    'plan_version': 1,
    'action_id': 'v1:contrast_ct',
    'raw_llm_detected': True,
    'rule_verified': True,
    'raw_llm_detected_and_verified': True,
    'rule_detected': True}],
  'raw_llm': {'detected': 2,
   'total': 2,
   'findings': [{'code': 'contrast_renal_precondition_missing',
     'severity': 'critical',
     'category': 'procedural',
     'plan_version': 1,
     'action_id': 'v1:contrast_ct',
     'message': 'Отсутствует результат оценки функции почек, необходимый для выполнения КТ с контрастом.',
     'evidence_ids': ['demo-policy-renal-contrast'],
     'patient_evidence': 'В patient_states отсутствуют данные о креатинине или eGFR на день принятия решения (день 0).',
     'recommendation': 'Отменить или перенести процедуру КТ с контрастом до получения результатов оценки функции почек.',
     'origin': 'llm',
     'status': 'open'},
    {'code': 'procedure_consent_missing',
     'severity': 'critical',
     'category': 'procedural',
     'plan_version': 1,
     'action_id': 'v1:contrast_ct',
     'message': 'Отсутствует зарегистрированное согласие пациента на проведение процедуры КТ с контрастом.',
     'evidence_ids': ['demo-policy-consent'],
     'patient_evidence': 'В patient_states отсутствует запись о согласии на процедуру в объекте consents.',
     'recommendation': 'Получить письменное согласие пациента перед выполнением процедуры.',
     'origin': 'llm',
     'status': 'open'}]},
  'rule_verification': {'confirmed': 2,
   'total': 2,
   'accepted_findings': 2,
   'unverified_findings': []},
  'rule_audit': {'detected': 2, 'total': 2},
  'other_rule_findings': [{'code': 'action_outside_catalog',
    'severity': 'critical',
    'category': 'citation',
    'plan_version': 1,
    'action_id': 'v1:contrast_ct',
    'message': 'Действие отсутствует в проверенном каталоге прототипа.',
    'evidence_ids': [],
    'patient_evidence': 'catalog_id=contrast_ct',
    'recommendation': 'Передать на ручную проверку; не считать действие обоснованным.',
    'origin': 'rule',
    'status': 'open'},
   {'code': 'renal_data_missing',
    'severity': 'critical',
    'category': 'uncertainty',
    'plan_version': 1,
    'action_id': 'v1:ampicillin_iv',
    'message': 'Не подтверждена функция почек для применения таблицы доз в заданных условиях.',
    'evidence_ids': ['cap-biochemistry',
     'cap-dose-scope',
     'demo-policy-dose-scope'],
    'patient_evidence': 'Нет результата: creatinine, egfr',
    'recommendation': 'Получить результаты; назначенный анализ не является полученным результатом.',
    'origin': 'rule',
    'status': 'open'}],
  'audited_traces': 1,
  'evaluated_faults': 2,
  'note': 'Две процедурные цели в одном синтетическом плане проверены одним вызовом LLM. Это требования демонстрационных политик, а не универсальные противопоказания. Правила и верификация не засчитываются как raw-обнаружение модели; прочие rule-находки перечислены отдельно.',
  'report': 'fault_llm_procedure.json'},
 'retrieval': {'queries': 10,
  'reference_recall_at_5': 0.85,
  'reference_hit_at_5': 0.9,
  'mean_recall_at_5': 0.85,
  'hit_at_5': 0.9,
  'note': 'Покрытие эталонных фрагментов текстом только top-5 найденных чанков, без соседей. mean_recall_at_5 и hit_at_5 — совместимые псевдонимы reference-метрик; это не recall идентификаторов автоматического индекса.',
  'results': [{'query': 'Какой стартовый антибиотик рекомендован при нетяжёлой внебольничной пневмонии в стационаре без значимых сопутствующих заболеваний?',
    'expected_ids': ['cap-empiric', 'cap-inpatient-table'],
    'actual_ids': ['ru-cap-654_2-2024:p024:0-4026:4e71fb2da3',
     'ru-cap-654_2-2024:p066:0-1060:ec683a8da8',
     'ru-cap-654_2-2024:p025:2108-4644:797d49dcf6',
     'demo-policy-comorbidity-scope',
     'ru-cap-654_2-2024:p022:0-4097:01c876882b'],
    'covered_reference_ids': ['cap-antibiotic-timing',
     'cap-empiric',
     'cap-inpatient-table',
     'cap-no-routine-combination',
     'cap-parenteral',
     'cap-risk-stratification'],
    'reference_recall_at_5': 1.0,
    'reference_hit_at_5': True},
   {'query': 'Чем заменить пенициллины при аллергической реакции немедленного типа на бета-лактамные антибиотики?',
    'expected_ids': ['cap-beta-allergy'],
    'actual_ids': ['ru-cap-654_2-2024:p025:0-2661:688843605a',
     'ru-cap-654_2-2024:p021:2262-4272:32d319cb31',
     'ru-cap-654_2-2024:p062:0-3752:c3d496b013',
     'ru-cap-654_2-2024:p061:0-2459:45901d1689',
     'ru-cap-654_2-2024:p027:0-4502:a4f2ff81ef'],
    'covered_reference_ids': ['cap-beta-allergy',
     'cap-fluoroquinolones',
     'cap-no-routine-combination'],
    'reference_recall_at_5': 1.0,
    'reference_hit_at_5': True},
   {'query': 'Какая доза и кратность внутривенного левофлоксацина указана в рекомендациях?',
    'expected_ids': ['cap-dose-levofloxacin'],
    'actual_ids': ['ru-cap-654_2-2024:p021:2262-4272:32d319cb31',
     'drug-levo-allergy',
     'ru-cap-654_2-2024:p030:0-2627:c050a56cc0',
     'drug-levo-qt',
     'ru-cap-654_2-2024:p064:0-2672:6c081e3cc5'],
    'covered_reference_ids': ['cap-dose-amoxiclav',
     'cap-dose-ampicillin',
     'cap-dose-levofloxacin',
     'cap-dose-scope'],
    'reference_recall_at_5': 1.0,
    'reference_hit_at_5': True},
   {'query': 'Какие биохимические показатели крови, функции почек и печени нужно исследовать госпитализированному пациенту?',
    'expected_ids': ['cap-biochemistry'],
    'actual_ids': ['ru-cap-654_2-2024:p042:0-2465:1e0a96f285',
     'demo-policy-renal-contrast',
     'ru-cap-654_2-2024:p065:0-2919:6f59368c7a',
     'ru-cap-654_2-2024:p014:0-3772:2de1772cc1',
     'ru-cap-654_2-2024:p013:0-3143:3cd492287a'],
    'covered_reference_ids': ['cap-biochemistry',
     'cap-cbc',
     'cap-crp',
     'cap-history',
     'cap-pulse-oximetry',
     'cap-vitals'],
    'reference_recall_at_5': 1.0,
    'reference_hit_at_5': True},
   {'query': 'Когда следует получить мокроту для посева относительно начала антибактериальной терапии?',
    'expected_ids': ['cap-sputum-before-antibiotics'],
    'actual_ids': ['ru-cap-654_2-2024:p028:0-4241:d7d462548a',
     'ru-cap-654_2-2024:p029:0-3728:4f7fa618b9',
     'ru-cap-654_2-2024:p023:0-4029:5d384f2f54',
     'ru-cap-654_2-2024:p063:0-3086:8880e573e4',
     'ru-cap-654_2-2024:p022:0-4097:01c876882b'],
    'covered_reference_ids': ['cap-crp-dynamics',
     'cap-culture-review',
     'cap-oral-switch-1',
     'cap-oral-switch-2',
     'cap-qt',
     'cap-reassess-72h',
     'cap-treatment-failure'],
    'reference_recall_at_5': 0.0,
    'reference_hit_at_5': False},
   {'query': 'Для чего госпитализированному пациенту с пневмонией делать ЭКГ и оценивать интервал QT?',
    'expected_ids': ['cap-ecg'],
    'actual_ids': ['ru-cap-654_2-2024:p019:0-4458:8f446936a7',
     'ru-cap-654_2-2024:p038:0-2557:4b7dbf1473',
     'ru-cap-654_2-2024:p063:0-3086:8880e573e4',
     'ru-cap-654_2-2024:p038:2087-4358:59092084cc',
     'ru-cap-654_2-2024:p042:1892-4146:a7798ef9f0'],
    'covered_reference_ids': ['cap-ecg', 'cap-qt'],
    'reference_recall_at_5': 1.0,
    'reference_hit_at_5': True},
   {'query': 'Как оценивать эффективность и безопасность стартовой антибиотикотерапии через 48–72 часа?',
    'expected_ids': ['cap-reassess-72h'],
    'actual_ids': ['ru-cap-654_2-2024:p042:1892-4146:a7798ef9f0',
     'ru-cap-654_2-2024:p022:0-4097:01c876882b',
     'ru-cap-654_2-2024:p028:0-4241:d7d462548a',
     'ru-cap-654_2-2024:p029:0-3728:4f7fa618b9',
     'ru-cap-654_2-2024:p026:0-4075:caa06c3d59'],
    'covered_reference_ids': ['cap-crp-dynamics',
     'cap-culture-review',
     'cap-oral-switch-1',
     'cap-oral-switch-2',
     'cap-reassess-72h',
     'cap-treatment-failure'],
    'reference_recall_at_5': 1.0,
    'reference_hit_at_5': True},
   {'query': 'Как использовать результаты микробиологических исследований для пересмотра лечения при его неэффективности?',
    'expected_ids': ['cap-culture-review', 'cap-etiotropic'],
    'actual_ids': ['ru-cap-654_2-2024:p028:0-4241:d7d462548a',
     'ru-cap-654_2-2024:p016:0-4195:4320e0bb09',
     'ru-cap-654_2-2024:p040:0-3542:9cc6025258',
     'ru-cap-654_2-2024:p022:0-4097:01c876882b',
     'ru-cap-654_2-2024:p060:0-3794:8f859f250a'],
    'covered_reference_ids': ['cap-crp-dynamics',
     'cap-culture-interpretation',
     'cap-culture-review',
     'cap-oral-switch-1',
     'cap-reassess-72h',
     'cap-sputum-before-antibiotics',
     'cap-treatment-failure'],
    'reference_recall_at_5': 0.5,
    'reference_hit_at_5': True},
   {'query': 'Какие критерии клинической стабильности должны присутствовать для перевода антибиотика с парентерального на пероральный приём?',
    'expected_ids': ['cap-oral-switch-1', 'cap-oral-switch-2'],
    'actual_ids': ['ru-cap-654_2-2024:p028:0-4241:d7d462548a',
     'ru-cap-654_2-2024:p066:0-1060:ec683a8da8',
     'ru-cap-654_2-2024:p043:0-2306:fa35edce95',
     'ru-cap-654_2-2024:p029:0-3728:4f7fa618b9',
     'ru-cap-654_2-2024:p039:0-3394:a8dbc6b9c8'],
    'covered_reference_ids': ['cap-crp-dynamics',
     'cap-culture-review',
     'cap-oral-switch-1',
     'cap-oral-switch-2',
     'cap-reassess-72h',
     'cap-treatment-failure'],
    'reference_recall_at_5': 1.0,
    'reference_hit_at_5': True},
   {'query': 'Какие рекомендации даны пациенту с пневмонией по жидкости и физической нагрузке?',
    'expected_ids': ['cap-hydration'],
    'actual_ids': ['ru-cap-654_2-2024:p068:2439-4705:ebb720317e',
     'ru-cap-654_2-2024:p036:0-2824:11294208ca',
     'ru-cap-654_2-2024:p023:0-4029:5d384f2f54',
     'ru-cap-654_2-2024:p043:0-2306:fa35edce95',
     'ru-cap-654_2-2024:p018:0-3966:c09e0315a8'],
    'covered_reference_ids': ['cap-chest-xray', 'cap-hydration'],
    'reference_recall_at_5': 1.0,
    'reference_hit_at_5': True}]},
 'usage': {'model': 'ministral-8b-latest',
  'api_attempts': 3,
  'cache_hits': 0,
  'usage': {'prompt_tokens': 48676,
   'completion_tokens': 1511,
   'total_tokens': 50187},
  'max_calls': 4,
  'max_output_tokens': 2400,
  'records': [{'role': 'auditor',
    'cache': False,
    'request_hash': '551941c35a4c0441b2ad4c7b075fd6e82a82a2a8f7b6926d00d2d5cc36c726cc',
    'model': 'ministral-14b-latest',
    'usage': {'prompt_tokens': 15751,
     'total_tokens': 16192,
     'completion_tokens': 441,
     'prompt_tokens_details': {'cached_tokens': 554},
     'service_tier': 'standard'}},
   {'role': 'auditor',
    'cache': False,
    'request_hash': '6599acad081e034a9cf61d3a81130abb7eee102e2ba8e8358fdb31e735381a56',
    'model': 'ministral-14b-latest',
    'usage': {'prompt_tokens': 17192,
     'total_tokens': 17599,
     'completion_tokens': 407,
     'prompt_tokens_details': {'cached_tokens': 0},
     'service_tier': 'standard'}},
   {'role': 'auditor',
    'cache': False,
    'request_hash': 'ea0d1bf596bcb5363e5da49f2f223e8ff87d446d470dfc3afcba0b5f02537550',
    'model': 'ministral-14b-latest',
    'usage': {'prompt_tokens': 15733,
     'total_tokens': 16396,
     'completion_tokens': 663,
     'prompt_tokens_details': {'cached_tokens': 0},
     'service_tier': 'standard'}}]}}